<!-- einfach nur ein leeres File -->
<div class="activities_right">
  <div>Irgendwas</div>
  <h3>Headline</h3>
  <img src="http://lorempizza.com/120/120" alt="">
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam deleniti, fugit dolorem saepe consequatur quia. Repudiandae nisi numquam iusto vero possimus in, soluta reiciendis. Vel error mollitia dolorem ad consequatur?</p>
  <a href="#">Weiterlesen</a>
</div>
