
    <li>
      <h3>Radbörse</h3>
      <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <ol>
          <li>
            <time>2009</time>
            <a href="#more">Auch die 19. Radbörse war ein...</a>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <a href="#more">mehr...</a></p>
          </li>
          <li>
            <time>2008</time>
            <a href="">1600 Euros Erlös bei der 18. Kuppenheimer Fahrradbörse</a>
          </li>
          <li>
            <time>2007</time>
            <a href="">1600 Euros Erlös bei der 18. Kuppenheimer Fahrradbörse</a>
          </li>
        </ol>
      </div>
    </li>
