<link rel="stylesheet" href="../../css/tdh/modules/content-widget-background.css" media="screen" title="no title" charset="utf-8">

<div class="colored-wrapper">
  <h2>Die Macher</h2>
  <ul>
    <li><a href="#">Macher Vorname Nachname</a></li>
    <li><a href="#">Macher Vorname Nachname</a></li>
    <li><a href="#">Macher Vorname Nachname</a></li>
    <li><a href="#">Macher Vorname Nachname</a></li>
  </ul>
  <a href="#">Alle Macher</a>
</div>

<div class="colored-wrapper clearfix">
  <h2>Das Team</h2>
  <img src="../images/team-beispielbild.jpg" alt="Teamfoto" />
  <p>
    Schreiben Sie uns eine <a href="#">E-Mail</a> oder rufen Sie einen
    <a href="#">Mitarbeiter</a> an, wir informieren Sie gerne persönlich.
  </p>
  <a href="#">Hier finden Sie eine Liste all unserer aktiven Mitarbeiter</a>
</div>

<div class="colored-wrapper">
  <h2>Unsere Spendenkonten</h2>
  <div class="container-left">
    <ul>
      <li><strong>Sparkasse</strong></li>
      <li>Baden-Baden / Gaggenau</li>
      <li><strong>Konto Nr.</strong> 120 790</li>
      <li><strong>BLZ</strong>  662 500 30</li>
    </ul>
  </div>
  <div class="container-right">
    <ul>
      <li><strong>Sparkasse</strong></li>
      <li>Baden-Baden / Gaggenau</li>
      <li><strong>Konto Nr.</strong> 120 790</li>
      <li><strong>BLZ</strong>  662 500 30</li>
    </ul>
  </div>
</div>

<div class="colored-wrapper news-widget clearfix">
  <h3>Erdbeben in Haiti</h3>
  <div class="container-left">
    <p>
      Hier finden Sie alle wichtigen Meldungen zu den Erdbeben in Haiti.
      Bitte unterstützen Sie uns weiterhin mit Spenden. Ihre Spende -
      <strong>Stichwort= "Erdbeben Haiti"</strong>. Alle Spenden reichen wir
      weiter an die Partnerorganisation tdh Lausanne, die vor Ort Hilfe leistet.
    </p>
  </div>
  <div class="container-right">
    <div class="inner-container">
      <ul>
        <li><strong>Sparkasse</strong> 120 790</li>
        <li>Baden-Baden / Gaggenau</li>
        <li><strong>BLZ</strong>  662 500 30</li>
      </ul>
    </div>
    <div class="inner-container">
      <ul>
        <li><strong>Sparkasse</strong> 120 790</li>
        <li>Baden-Baden / Gaggenau</li>
        <li><strong>BLZ</strong>  662 500 30</li>
      </ul>
    </div>
  </div>

</div>
