<div class="colored-wrapper news-widget clearfix">
  <h3>Erdbeben in Haiti</h3>
  <div class="container-left">
    <p>
      Hier finden Sie alle wichtigen Meldungen zu den Erdbeben in Haiti.
      Bitte unterstützen Sie uns weiterhin mit Spenden. Ihre Spende -
      <strong>Stichwort= "Erdbeben Haiti"</strong>. Alle Spenden reichen wir
      weiter an die Partnerorganisation tdh Lausanne, die vor Ort Hilfe leistet.
    </p>
  </div>
  <div class="container-right">
    <div class="inner-container">
      <ul>
        <li><strong>Sparkasse</strong> 120 790</li>
        <li>Baden-Baden / Gaggenau</li>
        <li><strong>BLZ</strong>  662 500 30</li>
      </ul>
    </div>
    <div class="inner-container">
      <ul>
        <li><strong>Sparkasse</strong> 120 790</li>
        <li>Baden-Baden / Gaggenau</li>
        <li><strong>BLZ</strong>  662 500 30</li>
      </ul>
    </div>
  </div>

</div>
