<div class="colored-wrapper">
  <h2>Unsere Spendenkonten</h2>
  <div class="container-left">
    <ul>
      <li><strong>Sparkasse</strong></li>
      <li>Baden-Baden / Gaggenau</li>
      <li><strong>Konto Nr.</strong> 120 790</li>
      <li><strong>BLZ</strong>  662 500 30</li>
    </ul>
  </div>
  <div class="container-right">
    <ul>
      <li><strong>Sparkasse</strong></li>
      <li>Baden-Baden / Gaggenau</li>
      <li><strong>Konto Nr.</strong> 120 790</li>
      <li><strong>BLZ</strong>  662 500 30</li>
    </ul>
  </div>
</div>
