     <div class="spenden_icon"><img src="images/spenden-icon.png" alt="Spenden Icon"></div>
     <button type="submit" class="button">
      <div class="text">
        <div class="sicher_schnell">sicher &amp; schnell</div>
        <div class="online_spenden">online spenden</div>
      </div>
     </button>

    <div class="info_icon"><img src="images/info-icon.png" alt="Info Icon"></div>
    <button type="button" class="button2">
    <div class="text2">
      Unser Spendenkonto
    </div>
    </button>
