<!--  JG: Machen Sie daraus bitte zwei separate Dateien und binden Sie diese dann auch separat in die PHP-Datei(en) ein. -->

<div class="spenden_button">
  <div class="spenden_icon">
    <img src="images/spenden-icon.png" alt="Spenden Icon">
  </div>
  <button type="submit" class="button">
    <span class="text">
      <span class="sicher_schnell">sicher &amp; schnell</span>
      <span class="online_spenden">online spenden</span>
    </span>
  </button>
</div>
<div class="spendenkonto_button">
   <div class="info_icon"><img src="images/info-icon.png" alt="Info Icon"></div>
   <button type="button" class="button2">
   <span class="text2">
     Unser Spendenkonto
   </span>
   </button>
</div>
