     <div class="spenden_icon"><img src="tdh-Testprojekt-WS2015-2/dev/images/spenden-icon.png" alt="Spenden Icon"></div>
     <button type="submit" class="button">
      <div class="text">
        <div class="sicher_schnell">sicher & schnell</div>
        <div class="online_spenden">online spenden</div>
      </div>
     </button>

    <div class="info_icon"><img src="tdh-Testprojekt-WS2015-2/dev/images/info-icon.gif" alt="Info Icon"></div>
    <button type="button" class="button2">
    <div class="text2">
      Unser Spendenkonto
    </div>
    </button>
 
