<div class="content-widget">
<section>
  <header>
  <h3>Vorgestellt</h3>
  <h4>Franz Bürk - "der Feuermacher"</h4>
  </header>

  <article>
  <img src="images/fackelmann.jpg" alt="Fackelmann" />
  <p>
    Franz Bürk aus Achern - "der Feuermacher" - war eine große Bereicherung für das Kinderfest 2011, indem er jung und alt präsentierte, wie man man ohne technische Hilfsmittel Feuer erzeugen kann.
  </p>
  <ul>
    <li><a href="#">Mehr in den Meldungen</a></li>
  </ul>
  </article>
</section>
</div>
