
<!-- einfach nur ein leeres File -->
<div class="contact-x">

<h3>Kontakt mit terre des hommes Murgtal</h3>

<p>Schreiben Sie uns eine Nachricht - wir melden uns so schnell wie möglich bei Ihnen</p>


<div class="formular clearfix">
<from action="/">

<div class"anliegen">
        <label for="anliegen"><strong>Was ist Ihr Anliegen?</strong></label>
        <select id="anliegen">
          <option value="0" selected disabled>Allgemeines</option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
        </select>
         </div>

<p>Wählen Sie bitte aus, worum es Ihnen geht - so finden wir schneller den richtigen Ansprechpartner</p>

<div>
<label for="name"><strong>Ihr Name*</strong></label>
<input type"text" name="name" id="name" placeholder="Ihr Name" required>
</div>

<div>
<label for="email"><strong>Ihre E-Mail Adresse*</strong></label>
<input type"email" name="email" id="email" placeholder="Ihre E-Mail Adresse" required>
</div>

<div class="nachricht">
<label for="nachricht"><strong>Ihre Nachricht*</strong></label>
<textarea type"text" name="nachricht" id="nachricht" rows="11" placeholder="Ihre Nachricht an tdh Murgtal" required></textarea>



<p>Hinterlassen Sie hier auch ihre Adresse oder Telefonnummer, wenn Sie möchten, dass wir telefonisch oder schriftlich mit Ihnen in Kontakt treten</p>

</div>
<div class="button">

        <input type="button" value="Nachricht senden">
         </div>





</from>
</div>

</seite>
