<div class="contact">
    <h3>Kontakt mit terre des hommes Murgtal</h3>
    <p>Schreiben Sie uns eine Nachricht - wir melden uns so schnell wie möglich bei Ihnen</p>
    <form  class="formular clearfix">
        <label for="request">Was ist Ihr Anliegen?</label>
        <select id="request">
            <option>Allgemeines</option>
            <option>Default Option1</option>
            <option>Default Option2</option>    
        </select>
        <p>Wählen Sie bitte aus, worum es Ihnen geht - so finden wir schneller den richtigen Ansprechpartner</p>
        
        <label for="name">Ihr Name*</label>
        <input id="name" placeholder="Ihr Name">
        <label for="mail">Ihre E-Mail Adresse*</label>
        <input id="mail" type="email" placeholder="Ihre E-Mail Adresse">
        <label for="txt" class="distance">Ihre Nachricht*</label>
        
        <textarea  class="distance" id="txt" type="email" rows="10"  placeholder="Ihre Nachricht an tdh Murgtal"></textarea>
        <p class="help" >Hinterlassen Sie hier auch ihre Adresse oder Telefonnummer, wenn Sie möchten, dass wir telefonisch oder schriftlich mit Ihnen in Kontakt treten.</p>
        
        <button class="send">Nachricht senden</button>
        
    </form>
</div>