<p><strong>Was wollen Sie sehen?</strong></p>
<form>
	<select>
	  <option value="A">A</option>
	  <option value="B">B</option>
	  <option value="C">C</option>
	  <option value="D">D</option>
	</select>

	<select>
	  <option value="1">1</option>
	  <option value="2">2</option>
	  <option value="3">3</option>
	  <option value="4">4</option>
	</select>
</form>
<p>Auswahl treffen und dann</p>


<table class="sponsors">
		<tr>
			<td class="cell-1"><img src="images/adler-apotheke.gif"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">x Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><img src=""><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">x Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">x Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">x Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">y Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">y Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">y Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
		<tr>
			<td class="cell-1"><p>Data Cell 01</p></td>
			<td class="cell-2">Data Cell 02</td>
		</tr>
	</tbody>
</table>
	