
<div class="sponsors">
	
	<p><strong>Was wollen Sie sehen?</strong></p>
	<form class="form_selection">
		<select class="sel_character">
		  <option value="A">A</option>
		  <option value="B">B</option>
		  <option value="C">C</option>
		  <option value="D">D</option>
		</select>
	
		<select class="sel_town">
		  <option value="1">Kuppenheim</option>
		  <option value="2">Bischweiler</option>
		  <option value="3">Karlsruhe</option>
		  <option value="4">Gernsbach-Scheuern</option>
		</select>
	</form>


	<p class="form_selection1"><strong>Auswahl treffen und dann</strong>
	<input type="submit" value="Inhalt sortieren"><a href=""></a></p>
	
	
	<table class="sponsor_list">
        <tbody>
			<tr>
				<td class="cell-1"><img src="images/adler-apotheke.gif"><p>Adler Apotheke</p></td>
				<td class="cell-2">Kupppenheim</td>
			</tr>
			<tr>
				<td class="cell-1"><p>ABAKU Computer</p></td>
				<td class="cell-2">Kuppenheim</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Adam Versicherungen</p></td>
				<td class="cell-2">Bischweiler</td>
			</tr>
			<tr>
				<td class="cell-1"><img src=""><p>Abacus Nachhilfeinstitut</p></td>
				<td class="cell-2">Gernsbach-Scheuern</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Adolph Präsente</p></td>
				<td class="cell-2">Karlsruhe</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">x Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">x Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">y Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">y Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">y Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
			<tr>
				<td class="cell-1"><p>Data Cell 01</p></td>
				<td class="cell-2">Data Cell 02</td>
			</tr>
		</tbody>
	</table>
</div>

