<div class="table-emp">
    <p>Hier finden Sie eine Liste all unserer aktiven Mitarbeiter</p>
    <p> Mit der Karte können Sie feststellen, wer von uns wo aktiv und ansprechbar ist</p>
    
    
    <table class="tablesorter" id="table-id">
        <thead>
            <tr>
                <th class='sort-default form'>Name</th>
                <th class='no-sort'>Telefon</th>
                <th class='sort-default form'>Ort</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Schlaffer, Willy</td>
                <td>07225/12345</td>
                <td>Germersbach-Scheuern</td>
            </tr>
            <tr>
                <td>Hartwigsen, Johannes</td>
                <td>07225/23456</td>
                <td>Mainz</td>
            </tr>
            <tr>
                <td>Schwellung, Rosa</td>
                <td>07225/34567</td>
                <td>Rüsselsheim</td>
            </tr>
            <tr>
                <td>Arbeit, Andi</td>
                <td>07225/45678</td>
                <td>Frankfurt a. M.</td>
            </tr>
            <tr>
                <td>Hose, Kurt C.</td>
                <td>07225/56789</td>
                <td>Viernheim</td>
            </tr>
            <tr>
                <td>Johanna, Marie</td>
                <td>07225/67890</td>
                <td>Bergisch Gladbach</td>
            </tr>
            <tr>
                <td>Fährlich, Sergej</td>
                <td>07225/78901</td>
                <td>Bielefeld</td>
            </tr>
            <tr>
                <td>Stein, Shawn</td>
                <td>07225/89012</td>
                <td>Brasilien</td>
            </tr>
            <tr>
                <td>Panse, Jim</td>
                <td>07225/90123</td>
                <td>Frankfurt a. O.</td>
            </tr>
        </tbody>
    </table>
    
</div>
